name: App Deploy to GitHub Pages

on:
  push:
    tags:
      - "*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install --force --ignore-scripts

      - name: Build Angular App
        run: ng build --configuration production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: dist/web-app/browser

  release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set version from tag
        run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "VERSION: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

      - name: Run release action
        uses: dimi7rof/create-release@v3
        with:
          name: dimi7rof.github.io
          version: ${{ env.VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
