name: Deploy App to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      Final:
        required: false
        default: false
        type: boolean
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --configuration production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: dist/web-app/browser

  release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get last tag and increment version
        if: ${{ github.event.inputs.Final != 'true' }}
        id: version
        run: |
          branch_name="${GITHUB_REF##*/}"
          last_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Last tag: $last_tag"
          if [[ "$last_tag" != "$branch_name"* ]]; then
            last_tag="${{ github.ref_name }}-dev.0"
            echo "No tag for branch, using: $last_tag"
          fi
          IFS='.' read -ra parts <<< "$last_tag"
          echo "Parts: ${parts[*]}"
          last_index=$((${#parts[@]} - 1))
          echo "Last index: $last_index"
          parts[$last_index]=$((parts[$last_index] + 1))
          echo "Updated parts: ${parts[*]}"
          new_version="${parts[*]}"
          echo "New version before formatting: $new_version"
          new_version="${new_version// /"."}"
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV
          echo "VERSION: $new_version" >> $GITHUB_STEP_SUMMARY

      - name: Run release action
        uses: dimi7rof/create-release@v3
        with:
          name: dimi7rof.github.io
          version: ${{ env.VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
