name: Deploy App to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: false
        default: "1.20.0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --configuration production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: dist/web-app/browser

  release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version || github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get last tag and increment version
        id: version
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          echo "Last tag: $last_tag"
          IFS='.' read -ra parts <<< "$last_tag"
          echo "Parts: ${parts[*]}"
          last_index=$((${#parts[@]} - 1))
          echo "Last index: $last_index"
          parts[$last_index]=$((parts[$last_index] + 1))
          echo "Updated parts: ${parts[*]}"
          new_version="${parts[*]}"
          echo "New version before formatting: $new_version"
          new_version="${new_version// /"."}"
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV
          echo "VERSION: $new_version" >> $GITHUB_STEP_SUMMARY

      - name: Use version
        run: echo "Version is ${{ env.VERSION }}"

      - name: Run release action
        uses: dimi7rof/create-release@v3
        with:
          name: dimi7rof.github.io
          version: ${{ env.VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
