name: Release [PR titles]

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Calculate Next Tag
        id: next_tag
        run: |
          IFS='.' read -r major minor patch <<< "$latest_tag"
          bump_type="${{ github.event.inputs.version_bump || 'patch' }}"
          echo "Version bump type: $bump_type"
          case "$bump_type" in
            major) major=$((major + 1)); minor=0; patch=0 ;;
            minor) minor=$((minor + 1)); patch=0 ;;
            patch) patch=$((patch + 1)) ;;
            *) echo "Invalid version bump type"; exit 1 ;;
          esac
          new_tag="$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"

      - name: Run release action
        uses: dimi7rof/create-release@v3
        with:
          name: Dimi7rof's CV app
          version: ${{ env.new_tag }}
          Team_webhook: ${{ '' }}
          github-token: ${{ github.token }}
